export const CSQuestions = [
    {
        prompt: "Which of the following is an example of effective communication?",
        optionA: "Speaking in a monotone voice",
        optionB: "Using technical jargon",
        optionC: "Speaking clearly and concisely",
        optionD: "Talking over others",
        answer: "optionC",
    },
    {
        prompt: "Which of the following is an example of nonverbal communication?",
        optionA: "Facial expressions",
        optionB: "Written emails",
        optionC: "Phone calls",
        optionD: "Video conferences",
        answer: "optionA",
    },
    {
        prompt: "Which of the following is an example of active listening?",
        optionA: "Interrupting the speaker",
        optionB: "Not focusing completely",
        optionC: "Paying attention to the speaker",
        optionD: "Texting while the speaker talks",
        answer: "optionC",
    },
    {
        prompt: "Which of the following is an example of effective feedback?",
        optionA: "Giving specific feedback",
        optionB: "Criticize character not behavior",
        optionC: "Providing vague feedback",
        optionD: "Withholding feedback",
        answer: "optionA",
    },
    {
        prompt: "Which of the following is an example of cultural sensitivity in communication?",
        optionA: "Universal norms assumption",
        optionB: "Using sarcasm or humor",
        optionC: "Respecting cultural differences",
        optionD: "Ignoring cultural differences",
        answer: "optionC",
    },
    {
        prompt: "Which of the following is an example of clear and concise writing?",
        optionA: "Using complex sentences",
        optionB: "Using technical acronyms",
        optionC: "Writing simple sentences",
        optionD: "Using slang language",
        answer: "optionC",
    },
    {
        prompt: "Which of the following is an example of assertive communication?",
        optionA: "Being overly aggressive",
        optionB: "Standing up for yourself",
        optionC: "Letting your advantage be taken",
        optionD: "Avoiding conflict at all costs",
        answer: "optionB",
    },
    {
        prompt: "Which of the following is an example of effective communication in a team setting?",
        optionA: "Ignoring others' perspectives",
        optionB: "Criticizing others' ideas",
        optionC: "Listening and empathizing",
        optionD: "Ignoring team members' input",
        answer: "optionC",
    }
];
