# Generated by Django 4.2.7 on 2023-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_title', models.CharField(max_length=255)),
                ('discussion_text', models.TextField()),
                ('admin_approved', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
