# Generated by Django 4.2.7 on 2023-11-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
