# Generated by Django 4.2.7 on 2023-11-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0002_discuss_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
