# Generated by Django 4.2.7 on 2023-11-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0005_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=255)),
                ('quiz_name', models.CharField(default='x', max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='announcements',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
