# Generated by Django 4.2.7 on 2023-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0006_leaderboard_announcements_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='username',
            field=models.CharField(default='Anonymous', max_length=255, primary_key=True, serialize=False),
        ),
    ]
