# Generated by Django 4.2.7 on 2023-11-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0008_leaderboard_id_alter_leaderboard_username_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=set(),
        ),
    ]
