# Generated by Django 4.2.7 on 2023-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd', '0010_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
