# Generated by Django 4.2.7 on 2023-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bknd", "0011_alter_discuss_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pastEvents")),
            ],
        ),
        migrations.CreateModel(
            name="pastEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("images", models.ManyToManyField(to="bknd.images")),
            ],
        ),
    ]
