# Generated by Django 4.2.7 on 2023-11-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bknd", "0012_images_pastevents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pastevents",
            name="images",
        ),
        migrations.AddField(
            model_name="pastevents",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bknd.images",
            ),
        ),
    ]
