# Generated by Django 4.2.7 on 2023-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bknd", "0013_remove_pastevents_images_pastevents_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                upload_to="frontend/src/component/images/pastEvents"
            ),
        ),
        migrations.RemoveField(
            model_name="pastevents",
            name="images",
        ),
        migrations.AddField(
            model_name="pastevents",
            name="images",
            field=models.ManyToManyField(to="bknd.images"),
        ),
    ]
