# Generated by Django 4.2.7 on 2023-11-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bknd", "0014_alter_images_image_remove_pastevents_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discuss",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
